apiVersion: v1
kind: Secret
metadata:
  name: glab-identity-db-secret
type: Opaque
data:
  DB_HOST: NDQuMjMxLjI0LjU4Cg==
  DB_NAME: aWRlbnRpdHkK
  DB_USER: aWR1c2VyCg==
  DB_PASSWORD: MnQ1OGNoRWVUTAo=
