apiVersion: apps/v1
kind: Deployment
metadata:
  name: glab-identity-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glab-identity-service
  template:
    metadata:
      labels:
        app: glab-identity-service
    spec:
      containers:
        - image: $IMAGE
          name: glab-identity-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: glab-identity-db-secret
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: glab-identity-db-secret
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: glab-identity-db-secret
                  key: DB_USER
            - name: DB_PWD
              valueFrom:
                secretKeyRef:
                  name: glab-identity-db-secret
                  key: DB_PWD
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-key-secret
                  key: JWT_SECRET_KEY
      imagePullSecrets: #Secret on Kubernetes cluster.  Values come from GitLab, see below
        - name: glab-identity-deploy-token