apiVersion: v1
kind: Service
metadata:
  name: glab-identity-service
spec:
  type: LoadBalancer
  selector:
    app: glab-identity-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http